# Generated by Django 5.2.4 on 2026-02-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgen', '0005_systemlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='squadron',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='squadronmembership',
            name='squadron',
        ),
        migrations.RemoveField(
            model_name='squadronmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.DeleteModel(
            name='GenerationHistory',
        ),
        migrations.DeleteModel(
            name='Squadron',
        ),
        migrations.DeleteModel(
            name='SquadronMembership',
        ),
    ]
