# Generated by Django 5.2.4 on 2026-06-02 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password_security", "0003_alter_passwordanalysis_pii_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordanalysis",
            name="password_hash",
            field=models.CharField(
                help_text="SHA-256 of password for duplicate detection only (not for auth)",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordanalysis",
            index=models.Index(
                fields=["user", "created_at"], name="password_se_user_id_d35823_idx"
            ),
        ),
    ]
