# Generated by Django 5.2.4 on 2026-03-01 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='wordlist_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['user', 'timestamp'], name='generator_g_user_id_6f94d8_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['wordlist_count'], name='generator_g_wordlis_b45595_idx'),
        ),
    ]
