# Generated by Django 5.2.4 on 2026-03-18 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pii_data', models.JSONField(blank=True, default=dict)),
                ('password_hash', models.CharField(max_length=128)),
                ('vulnerability_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('strength_score', models.PositiveIntegerField(default=0)),
                ('crack_time_estimate', models.CharField(blank=True, max_length=100)),
                ('breach_count', models.PositiveIntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('vulnerabilities_found', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Analysis',
                'verbose_name_plural': 'Password Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mode', models.CharField(choices=[('user', 'User Mode'), ('security', 'Security Mode')], default='user', max_length=20)),
                ('last_mode', models.CharField(choices=[('user', 'User Mode'), ('security', 'Security Mode')], default='user', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
