# Generated by Django 5.2.4 on 2025-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['timestamp'], name='wordgen_gen_timesta_39039b_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['ip_address'], name='wordgen_gen_ip_addr_0d3bec_idx'),
        ),
    ]
