# Generated by Django 5.2.4 on 2026-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_teams_team_invite__1f7990_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
