# Generated by Django 5.2.4 on 2026-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SUCCESS', 'Success')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(default='SYSTEM', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
