# Generated by Django 5.2.4 on 2026-03-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_systemlog_level_alter_systemlog_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SUCCESS', 'Success')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='source',
            field=models.CharField(default='SYSTEM', max_length=50),
        ),
    ]
