# Generated by Django 5.2.4 on 2026-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'User Login'), ('GENERATE', 'Wordlist Generated'), ('SCAN', 'Network Scan'), ('BREACH', 'Data Breach Detected'), ('SQUAD_JOIN', 'Squadron Joined')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(default='UNK', max_length=3)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('color', models.CharField(default='green', max_length=20)),
                ('intensity', models.FloatField(default=0.5)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='visualizati_timesta_7489ef_idx')],
            },
        ),
    ]
