# Generated by Django 5.2.4 on 2026-03-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='analytics_u_timesta_2b8b17_idx',
            old_name='visualizati_timesta_7489ef_idx',
        ),
    ]
