# Generated by Django 5.2.4 on 2026-03-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_visualizati_timesta_7489ef_idx_analytics_u_timesta_2b8b17_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('GENERATE', 'Wordlist Generated'), ('SCAN', 'Network Scan'), ('BREACH', 'Data Breach Detected'), ('SQUAD_JOIN', 'Squadron Joined'), ('TEAM_JOIN', 'Team Joined'), ('CONFIG', 'Configuration Change')], max_length=20),
        ),
    ]
