# Generated by Django 5.2.4 on 2026-06-02 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_useractivity_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "timestamp"], name="analytics_u_user_id_54ee7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="analytics_u_activit_f59ac3_idx",
            ),
        ),
    ]
