# Generated by Django 5.2.4 on 2026-03-02 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['invite_code'], name='teams_team_invite__1f7990_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['owner'], name='teams_team_owner_i_7dde75_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'role'], name='teams_teamm_team_id_4d95f6_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['joined_at'], name='teams_teamm_joined__179694_idx'),
        ),
        migrations.AddIndex(
            model_name='teammessage',
            index=models.Index(fields=['team', 'timestamp'], name='teams_teamm_team_id_4c3af8_idx'),
        ),
    ]
