# Generated by Django 5.2.4 on 2026-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_team_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
